routes/web.php
<?php

use \Illuminate\Support\Facades\Auth;
use \Illuminate\Support\Facades\Route;
use \App\Http\Controllers\SurveyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('survey', 'SurveyController')->middleware('verified');
Route::get('/survey/{survey}', [SurveyController::class, 'show'])
    ->name('survey.show');
Route::post('/survey/vote/{survey}', [SurveyController::class, 'vote'])
    ->name('survey.vote');
Route::post('/survey/share/{survey}', [SurveyController::class, 'share'])
    ->name('survey.share');

app/Survey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * Class Survey
 * @package App
 */
class Survey extends Model
{
    const COOKIE_NAME = 'zthasvt';
    const DATETIME_FORMAT = 'Y-m-d H:i';

    /**
     * @var array
     */
    protected $fillable = ['user_id', 'name', 'question', 'completed', 'expires_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function surveyoption()
    {
        return $this->hasMany(SurveyOption::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function surveyvote()
    {
        return $this->hasMany(SurveyVote::class);
    }

    /**
     * Custom sync functionality for the one to many relationship that'll keep the foreign key constraints intact
     *
     * @param array $surveyOptionRequest
     * @throws \Exception
     */
    public function syncSurveyOptions(array $surveyOptionRequest)
    {
        $surveyOptionData = $this->getSurveyOptions($surveyOptionRequest);
        $existingOptions = [];

        /** @var SurveyOption $existingOption */
        foreach ($this->surveyoption->all() as $existingOption) {
            $existingOptions[$existingOption->id] = $existingOption;
        }

        $optionsToBeUpdated = array_intersect_key($existingOptions, $surveyOptionData);
        $optionsToBeAdded = array_diff_key($surveyOptionData, $existingOptions);
        $optionsToBeDeleted = array_diff_key($existingOptions, $surveyOptionData);

        /** @var SurveyOption $optionToBeUpdated */
        foreach ($optionsToBeUpdated as $optionToBeUpdatedId => $optionToBeUpdated) {
            $optionToBeUpdated->update(['option_text' => $surveyOptionData[$optionToBeUpdatedId]['option_text']]);
        }

        /** @var array $optionToBeAdded */
        foreach ($optionsToBeAdded as $optionToBeAdded) {
            $this->surveyoption()->create(['survey_id' => $this->id, 'option_text' => $optionToBeAdded['option_text']]);
        }

        /** @var SurveyOption $optionToBeDeleted */
        foreach ($optionsToBeDeleted as $optionToBeDeleted) {
            $optionToBeDeleted->delete();
        }
    }

    /**
     * @param array $surveyOptions
     * @return array
     */
    protected function getSurveyOptions(array $surveyOptions)
    {
        $options = [];

        if (count($surveyOptions) > 0) {
            foreach ($surveyOptions as $id => $option) {
                $options[$id] = ['id' => $id, 'option_text' => $option];
            }
        }

        return $options;
    }
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Surveys\CreateSurveysRequest;
use App\Http\Requests\Surveys\UpdateSurveysRequest;
use App\Survey;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use App\Mail\SurveyShare;

/**
 * Class SurveyController
 * @package App\Http\Controllers
 */
class SurveyController extends Controller
{
    /**
     * SurveyController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['show', 'vote']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('survey.index')->with('surveys', Survey::where('user_id', auth()->user()->id)->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Request $request)
    {
        return view('survey.create')->with('request', $request);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateSurveysRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function store(CreateSurveysRequest $request)
    {
        try {
            /** @var Survey $survey */
            $survey = Survey::create([
                'name' => $request->name,
                'question' => $request->question,
                'completed' => ($this->getCompleted($request->expires_at) === -1 ? 1 : 0),
                'expires_at' => $request->expires_at,
                'user_id' => auth()->user()->id,
            ]);
            $survey->syncSurveyOptions($request->option);
        } catch (\Exception $exception) {
            session()->flash('error', __('An error occurred while creating the Survey. Please try again.'));

            return redirect(route('survey.create'));
        }

        session()->flash('success', __('Survey created successfully'));

        return redirect(route('survey.edit', $survey->id));
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @param Survey $survey
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request, Survey $survey)
    {
        $cookieIsSet = ($request->cookie($this->getCookieName((int)$survey->id)) ? true : false);
        $votes = $this->getVoteCounts((int)$survey->id);

        return view('survey.show')
            ->with('survey', $survey)
            ->with('cookieIsSet', $cookieIsSet)
            ->with('votes', $votes);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Survey $survey
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function edit(Survey $survey)
    {
        if ((int)auth()->user()->id !== (int)$survey->user->id) {
            throw new \Exception('Unauthorised action');
        }

        return view('survey.create')->with('survey', $survey);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateSurveysRequest $request
     * @param Survey $survey
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function update(UpdateSurveysRequest $request, Survey $survey)
    {
        $error = false;
        $message = 'Survey updated successfully';

        try {
            $survey->update([
                'name' => $request->name,
                'question' => $request->question,
                'completed' => ($this->getCompleted($request->expires_at) === -1 ? 1 : 0),
                'expires_at' => $request->expires_at,
            ]);
            $survey->syncSurveyOptions($request->option);
        } catch (\Exception $exception) {
            $error = true;
            $message = 'An error occurred while updating the Survey. Please try again.';
        }

        session()->flash(((bool)$error === true ? 'error' : 'success'), __($message));

        return redirect(route('survey.edit', $survey->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Survey $survey
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Survey $survey)
    {
        if ((int)auth()->user()->id !== (int)$survey->user->id) {
            throw new \Exception('Unauthorised action');
        }

        $survey->delete();

        session()->flash('success', __('Survey deleted successfully'));

        return redirect(route('survey.index'));
    }

    /**
     * @param Request $request
     * @param Survey $survey
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function vote(Request $request, Survey $survey)
    {
        $existingCookie = $request->cookie($this->getCookieName((int)$survey->id));

        if ($existingCookie) {
            session()->flash('success', __('You have already voted for this survey'));

            return redirect(route('survey.show', $survey->id))->cookie($existingCookie);
        }

        $surveyOptionId = (int)$request->option;
        $cookie = cookie(
            $this->getCookieName((int)$survey->id),
            Hash::make($survey->id . '-' . $surveyOptionId),
            60 * 24 * 365
        );

        $survey->surveyvote()->create([
            'survey_id' => (int)$survey->id,
            'survey_option_id' => $surveyOptionId,
            'cookie' => $cookie->getValue(),
        ]);

        session()->flash('success', __('You have voted successfully'));

        return redirect(route('survey.show', $survey->id))->cookie($cookie);
    }

    /**
     * @param Request $request
     * @param Survey $survey
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function share(Request $request, Survey $survey)
    {
        try {
            $error = false;
            $message = __('Survey shared successfully');
            $emails = explode(',', trim(str_replace(' ', '', $request->emails)));
            $content = [
                'from_email' => auth()->user()->email,
                'from_name' => auth()->user()->name,
                'subject' => __('A Survey was shared with you!'),
                'body' => __(
                    sprintf(
                        '%s shared the survey %s with you, please click the button below to cast your vote.',
                        auth()->user()->name,
                        $survey->name
                    )
                ),
                'buttonText' => __('Vote Now!'),
                'buttonUrl' => route('survey.show', $survey->id)
            ];

            Mail::to(auth()->user()->email)
                ->bcc($emails)
                ->send(new SurveyShare($content));
        } catch (\Exception $exception) {
            $error = true;
            $message = __('An error occurred while sharing the Survey, please try again');
        }

        session()->flash(((bool)$error === true ? 'error' : 'success'), __($message));

        return redirect(route('survey.edit', $survey->id));
    }

    /**
     * @param string $expiresAt
     * @return int
     */
    protected function getCompleted($expiresAt = '')
    {
        if (trim($expiresAt) === '') {
            return 0;
        }

        $dateNow = \DateTime::createFromFormat(Survey::DATETIME_FORMAT, date(Survey::DATETIME_FORMAT));
        $dateExpiresAt = \DateTime::createFromFormat(Survey::DATETIME_FORMAT, $expiresAt);

        return $dateExpiresAt <=> $dateNow;
    }

    /**
     * @param int $surveyId
     * @return string
     */
    protected function getCookieName(int $surveyId)
    {
        return Survey::COOKIE_NAME . '-' . $surveyId;
    }

    /**
     * @param int $surveyId
     * @return array
     */
    public function getVoteCounts(int $surveyId)
    {
        $votes = DB::table('surveys')
            ->select(
                'survey_votes.survey_option_id',
                DB::raw('COUNT(survey_votes.survey_option_id) AS vote_count')
            )
            ->join('survey_options', 'surveys.id', '=', 'survey_options.survey_id')
            ->join('survey_votes', function ($join) {
                $join->on('surveys.id', '=', 'survey_votes.survey_id')
                    ->on('survey_options.id', '=', 'survey_votes.survey_option_id');
            })
            ->where('surveys.id', $surveyId)
            ->groupBy('survey_votes.survey_option_id')
            ->orderBy('vote_count', 'desc')
            ->orderBy('survey_votes.survey_option_id')
            ->get()
            ->toArray();

        if (count($votes) === 0) {
            return ['max_vote_count' => 0];
        }

        $voteData = [];
        $mostVotes = reset($votes);
        $voteData['max_vote_count'] = $mostVotes->vote_count;

        foreach ($votes as $vote) {
            $voteData[$vote->survey_option_id] = [
                'vote_count' => $vote->vote_count,
                'count_percentage' => ($vote->vote_count / $voteData['max_vote_count']) * 100
            ];
        }

        return $voteData;
    }
}

resources/views/survey/create.blade.php
@extends('layouts.app')

@section('content')
    @php($newSurvey = isset($survey) ? false : true)
    <div class="card card-default">
        <div class="card-header">
            <h3 class="float-left align-middle m-0">
                {{ ($newSurvey === false) ? __('Edit Survey') : __('Create Survey') }}
            </h3>
        </div>
        <div class="card-body">
            @include('partials.errors')
            <form method="post"
                  action="{{ ($newSurvey === false) ? route('survey.update', $survey->id) : route('survey.store') }}"
                  id="form">
                @csrf
                @if($newSurvey === false)
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name">{{ __('Name') }}</label>
                    <input type="text" class="form-control" name="name" id="name"
                           value="{{ ($newSurvey === false) ? $survey->name : ($request->old('name') ? : '') }}"
                           required>
                    @error('name')
                    <span class="invalid-feedback" role="alert" style="display: block;">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="question">{{ __('Question') }}</label>
                    <textarea class="form-control" name="question" id="question" cols="30"
                              rows="10"
                              required>{{ ($newSurvey === false) ? $survey->question : ($request->old('question') ? : '') }}</textarea>
                    @error('question')
                    <span class="invalid-feedback" role="alert" style="display: block;">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="expires-at">{{ __('Expiry Date') }}</label>
                    <input type="text" class="form-control" name="expires_at" id="expires-at"
                           value="{{ ($newSurvey === false) ? $survey->expires_at  : ($request->old('expires_at') ? : '') }}">
                    @error('expires_at')
                    <span class="invalid-feedback" role="alert" style="display: block;">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <label class="form-group m-0" for="option-container">{{ __('Question Options') }}</label>
                <small
                    class="form-text text-muted">{{ __('Enter answer options to the Survey question. Click the Add Option button to add another answer option and click the Remove button next to an answer option to remove it.') }}</small>
                <div id="option-container">
                    @if($newSurvey === true)
                        @if(is_array($request->old('option')) && count($request->old('option')) > 0)
                            @foreach($request->old('option') as $id => $option)
                                <div class="form-row" id="form-row-option-{{ $id }}">
                                    <div class="form-group col-md-11">
                                        <input class="form-control option-input" type="text"
                                               name="option[{{ $id }}]" id="option-{{ $id }}"
                                               value="{{ $option }}" data-id="{{ $id }}">
                                    </div>
                                    <div class="form-group col-md-1">
                                        @if($id > 1)
                                            <button class="option-remove-button btn btn-danger"
                                                    type="button" onclick="removeFormRow('form-row-option-{{ $id }}')">
                                                {{ __('Remove') }}
                                            </button>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        @else
                            <div class="form-row" id="form-row-option-1">
                                <div class="form-group col-md-11">
                                    <input class="form-control option-input" type="text" name="option[1]" id="option-1"
                                           data-id="1">
                                </div>
                                <div class="form-group col-md-1"></div>
                            </div>
                        @endif
                    @else
                        @foreach($survey->surveyoption as $option)
                            <div class="form-row" id="form-row-option-{{ $option->id }}">
                                <div class="form-group col-md-11">
                                    <input class="form-control option-input" type="text"
                                           name="option[{{ $option->id }}]" id="option-{{ $option->id }}"
                                           value="{{ $option->option_text }}" data-id="{{ $option->id }}">
                                </div>
                                <div class="form-group col-md-1">
                                    <button class="option-remove-button btn btn-danger" type="button"
                                            onclick="removeFormRow('form-row-option-{{ $option->id }}')">
                                        {{ __('Remove') }}
                                    </button>
                                </div>
                            </div>
                        @endforeach
                    @endif
                    @error('option')
                    <span class="invalid-feedback" role="alert" style="display: block;">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="button" id="option-add-button"
                            class="btn btn-primary mb-2">{{ __('Add Option') }}</button>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-primary btn-block">{{ __('Save') }}</button>
                    @if((bool)$newSurvey === false)
                        <button type="button" class="btn btn-info btn-secondary btn-block"
                                onclick="handleShare({{ $survey->id }})">{{ __('Share') }}</button>
                        <button type="button" class="btn btn-danger btn-secondary btn-block"
                                onclick="handleDelete({{ $survey->id }})">{{ __('Delete') }}</button>
                    @endif
                </div>
            </form>
        </div>
    </div>
    @include('partials.deletemodal')
    @include('partials.sharemodal')
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

@section('scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#expires-at", {
            enableTime: true
        });

        function removeFormRow(idValue) {
            $('#' + idValue.toString()).remove();
        }

        function createFormRow(name, count) {
            var idAttribute = name.toLowerCase() + '-' + count.toString();
            var nameAttribute = name.toLowerCase() + '[' + count.toString() + ']';

            var optionInput = document.createElement('input');
            $optionInput = $(optionInput);
            $optionInput.addClass('form-control')
                .addClass('option-input')
                .attr('type', 'text')
                .attr('name', nameAttribute)
                .attr('id', idAttribute)
                .attr('data-id', count.toString());

            var optionGroup = document.createElement('div');
            $optionGroup = $(optionGroup);
            $optionGroup.addClass('form-group').addClass('col-md-11').append(optionInput);

            var removeButton = document.createElement('button');
            $removeButton = $(removeButton);
            $removeButton.addClass('option-remove-button')
                .addClass('btn')
                .addClass('btn-danger')
                .attr('type', 'button')
                .attr('onclick', 'removeFormRow(\'form-row-' + idAttribute + '\')')
                .text('Remove');

            var removeGroup = document.createElement('div');
            $removeGroup = $(removeGroup);
            $removeGroup.addClass('form-group').addClass('col-md-1').append(removeButton);

            var formRow = document.createElement('div');
            $formRow = $(formRow);
            $formRow.append(optionGroup)
                .append(removeGroup)
                .addClass('form-row')
                .attr('id', 'form-row-' + idAttribute);

            return formRow;
        }

        $('#option-add-button').click(
            function () {
                let optionCount;

                $('.option-input').each(function () {
                    if (!optionCount) {
                        optionCount = this;
                    } else {
                        if (parseInt($(this).data('id')) > parseInt($(optionCount).data('id'))) {
                            optionCount = this;
                        }
                    }
                });

                $('#option-container').append(createFormRow('Option', $(optionCount).data('id') + 1));
            }
        );

        function handleDelete(id) {
            var deleteForm = document.getElementById('deleteSurveyForm');
            deleteForm.action = '/survey/' + id;
            $('#deleteModal').modal('show');
        }

        function handleShare(id) {
            var shareForm = document.getElementById('shareSurveyForm');
            shareForm.action = '/survey/share/' + id;
            $('#shareModal').modal('show');
        }
    </script>
@endsection

resources/views/survey/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3 class="float-left align-middle m-0">{{ __('Surveys') }}</h3>
            <a href="{{ route('survey.create') }}" class="btn btn-success float-right">{{ __('Create Survey') }}</a>
        </div>
        <div class="card-body">
            @include('partials.errors')
            <table class="table">
                <thead>
                <tr class="d-flex">
                    <th class="col-4">{{ __('Name') }}</th>
                    <th class="col-4">{{ __('Expiry Date') }}</th>
                    <th class="col-4">&nbsp;</th>
                </thead>
                </tr>
                <tbody>
                @if($surveys->count() > 0)
                    @foreach($surveys as $survey)
                        <tr class="d-flex">
                            <td class="col-4">
                                <a href="{{ route('survey.show', $survey->id) }}">{{ $survey->name }}</a>
                            </td>
                            <td class="col-4">{{ $survey->expires_at }}</td>
                            <td class="col-4">
                                <div class="float-right">
                                    <a class="btn btn-info btn-sm" style="color: #000000;"
                                       href="{{ route('survey.edit', $survey->id) }}">{{ __('Edit') }}</a>
                                    <button type="button" class="btn btn-danger btn-sm"
                                            onclick="handleDelete({{ $survey->id }})">{{ __('Delete') }}</button>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr class="d-flex">
                        <td colspan="3" class="col-12">{{ __('No Surveys found') }}</td>
                    </tr>
                @endif
                </tbody>
            </table>
            @include('partials.deletemodal')
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function handleDelete(id) {
            var deleteForm = document.getElementById('deleteSurveyForm');
            deleteForm.action = '/survey/' + id;
            $('#deleteModal').modal('show');
        }
    </script>
@endsection

resources/views/survey/show.blade.php
@extends('layouts.app')

@section('content')
    @include('partials.errors')
    <div class="row">
        <div class="col">
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="float-left m-0">{{ $survey->name }}</h3>
                </div>
                <div class="card-body">
                    <div class="card-text">
                        <p>{{ $survey->question }}</p>
                        @if(trim($survey->expires_at) !== '')<p>{{ __('Expires at: ') . $survey->expires_at }}</p>@endif
                    </div>
                    @if((bool)$cookieIsSet === false && (bool)$survey->completed === false)
                        <form action="{{ route('survey.vote', $survey->id) }}" method="post" id="form">
                            @csrf
                            @foreach($survey->surveyoption as $surveyOption)
                                <div class="custom-control custom-radio" style="margin-bottom: .5rem;">
                                    <input type="radio" id="{{ 'option-' . $surveyOption->id }}" name="option"
                                           class="custom-control-input" value="{{ $surveyOption->id }}">
                                    <label class="custom-control-label"
                                           for="{{ 'option-' . $surveyOption->id }}">
                                        {{ $surveyOption->option_text }}
                                    </label>
                                </div>
                            @endforeach
                            <div class="form-group" style="margin-top: .5rem;">
                                <button type="submit"
                                        class="btn btn-success btn-primary btn-block">{{ __('Submit') }}</button>
                            </div>
                        </form>
                    @else
                        @foreach($survey->surveyoption as $surveyOption)
                            @php
                                $voteCount = array_key_exists($surveyOption->id, $votes) ?
                                    $votes[$surveyOption->id]['vote_count'] :
                                    0;
                                $countPercentage = array_key_exists($surveyOption->id, $votes) ?
                                    $votes[$surveyOption->id]['count_percentage'] :
                                    0;
                            @endphp
                            <div>
                                <strong>{{ $surveyOption->option_text }}</strong>
                                <span class="badge badge-primary float-right">
                                    {{ $voteCount . ' ' . ((int)$voteCount === 1 ? __('vote') : __('votes')) }}
                                </span>
                            </div>
                            <div class="progress" style="margin-bottom: 1rem; height: 20px;">
                                <div class="progress-bar bg-info" role="progressbar"
                                     style="color: #000000; width: {{ $countPercentage }}%"
                                     aria-valuenow="{{ $voteCount }}" aria-valuemin="0"
                                     aria-valuemax="{{ $votes['max_vote_count'] }}"></div>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection